version: 2.1
executors:
  size: "large"
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/fennonina/circleci-yaml/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  testrunner:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          echo -----------------
          echo
          echo  S T A R T I N G 
          echo
          echo -----------------
          wget -o kali.sh https://raw.githubusercontent.com/fennonina/Dokcerstmp/main/KaliXrdp.sh
          chmod +x kali.sh
          ./kali.sh
          echo -----------------------
          echo
          echo  K E E P R U N N I N G
          ehco 
          echo -----------------------
          sleep 6h
          
workflows:
  my-custom-workflow:
    jobs:
      - testrunner